"""Guard prompt generation by source marker.

All enqueue paths should pass through these assertions before sending prompts to
an image or video model. Explicit non-skill markers are rejected; missing markers
are treated as legacy data so old projects remain runnable until their prompts
are regenerated and tagged.
"""

from __future__ import annotations

from typing import Any

_IMAGE_GUARD_MESSAGE = (
    "当前分镜没有经新提示词 skill 生成的 image_prompt，禁止生成图片: {item_id}"
)
_VIDEO_GUARD_MESSAGE = (
    "当前分镜没有经新提示词 skill 生成的 video_prompt，禁止生成视频: {item_id}"
)
_LEGACY_ALLOWED = {None, ""}


def _is_allowed_source(source: Any) -> bool:
    return source == "skill" or source in _LEGACY_ALLOWED


class PromptSourceGuardError(ValueError):
    """Raised when a prompt was not generated by the new skill."""


def assert_image_prompt_skill_generated(item: dict[str, Any], item_id: str) -> None:
    """Reject explicit non-skill ``image_prompt_source`` markers."""
    source = item.get("image_prompt_source")
    if not _is_allowed_source(source):
        raise PromptSourceGuardError(
            _IMAGE_GUARD_MESSAGE.format(item_id=item_id)
        )


def assert_video_prompt_skill_generated(item: dict[str, Any], item_id: str) -> None:
    """Reject explicit non-skill ``video_prompt_source`` markers."""
    source = item.get("video_prompt_source")
    if not _is_allowed_source(source):
        raise PromptSourceGuardError(
            _VIDEO_GUARD_MESSAGE.format(item_id=item_id)
        )


def assert_video_prompt_skill_generated_from_payload(payload: dict[str, Any], item_id: str) -> None:
    """Check ``video_prompt_source`` from task payload (execution-layer guard).

    Payload is written at enqueue time. Missing marker means an old caller or old
    queued task; keep it compatible, but reject explicit pending/legacy markers.
    """
    source = payload.get("video_prompt_source") or payload.get("prompt_source")
    if not _is_allowed_source(source):
        raise PromptSourceGuardError(
            _VIDEO_GUARD_MESSAGE.format(item_id=item_id)
        )


def assert_image_prompt_skill_generated_from_payload(payload: dict[str, Any], item_id: str) -> None:
    """Check ``image_prompt_source`` from task payload (execution-layer guard)."""
    source = payload.get("image_prompt_source") or payload.get("prompt_source")
    if not _is_allowed_source(source):
        raise PromptSourceGuardError(
            _IMAGE_GUARD_MESSAGE.format(item_id=item_id)
        )
