"""Hard guard: block image/video generation unless prompt was created by new skill.

All three enqueue paths (SDK / WebUI / Worker) must call these assertions before
sending any prompt to an image or video model.  Only ``source == "skill"`` passes;
anything else — including missing, ``"pending"``, or ``"legacy"`` — is rejected.
"""

from __future__ import annotations

from typing import Any

_IMAGE_GUARD_MESSAGE = (
    "当前分镜没有经新提示词 skill 生成的 image_prompt，禁止生成图片: {item_id}"
)
_VIDEO_GUARD_MESSAGE = (
    "当前分镜没有经新提示词 skill 生成的 video_prompt，禁止生成视频: {item_id}"
)


class PromptSourceGuardError(ValueError):
    """Raised when a prompt was not generated by the new skill."""


def assert_image_prompt_skill_generated(item: dict[str, Any], item_id: str) -> None:
    """Hard-check: ``image_prompt_source`` must be ``"skill"``."""
    source = item.get("image_prompt_source")
    if source != "skill":
        raise PromptSourceGuardError(
            _IMAGE_GUARD_MESSAGE.format(item_id=item_id)
        )


def assert_video_prompt_skill_generated(item: dict[str, Any], item_id: str) -> None:
    """Hard-check: ``video_prompt_source`` must be ``"skill"``."""
    source = item.get("video_prompt_source")
    if source != "skill":
        raise PromptSourceGuardError(
            _VIDEO_GUARD_MESSAGE.format(item_id=item_id)
        )


def assert_video_prompt_skill_generated_from_payload(payload: dict[str, Any], item_id: str) -> None:
    """Check ``video_prompt_source`` from task payload (execution-layer guard).

    Payload is written at enqueue time; if the marker is missing treat as pending.
    """
    source = payload.get("video_prompt_source") or payload.get("prompt_source")
    if source != "skill":
        raise PromptSourceGuardError(
            _VIDEO_GUARD_MESSAGE.format(item_id=item_id)
        )


def assert_image_prompt_skill_generated_from_payload(payload: dict[str, Any], item_id: str) -> None:
    """Check ``image_prompt_source`` from task payload (execution-layer guard)."""
    source = payload.get("image_prompt_source") or payload.get("prompt_source")
    if source != "skill":
        raise PromptSourceGuardError(
            _IMAGE_GUARD_MESSAGE.format(item_id=item_id)
        )
